// AUTO-GENERATED by scripts/generate-schemas.ts — do not edit by hand.
import S0 from '../schemas/Status.schema.json';
import S1 from '../schemas/Phase.schema.json';
import S2 from '../schemas/Timeline.schema.json';
import S3 from '../schemas/SubSpec.schema.json';
import S4 from '../schemas/CrossRef.schema.json';
import S5 from '../schemas/AgentAllocation.schema.json';
import S6 from '../schemas/Team.schema.json';
import S7 from '../schemas/Reviewer.schema.json';
import S8 from '../schemas/OpenQuestion.schema.json';
import S9 from '../schemas/Risk.schema.json';
import S10 from '../schemas/Mockup.schema.json';
import S11 from '../schemas/Chart.schema.json';
import S12 from '../schemas/AgentTree.schema.json';

export type ComponentName =
  | 'Status'
  | 'Phase'
  | 'Timeline'
  | 'SubSpec'
  | 'CrossRef'
  | 'AgentAllocation'
  | 'Team'
  | 'Reviewer'
  | 'OpenQuestion'
  | 'Risk'
  | 'Mockup'
  | 'Chart'
  | 'AgentTree';

export const schemas: Record<ComponentName, unknown> = {
  Status: S0 as unknown,
  Phase: S1 as unknown,
  Timeline: S2 as unknown,
  SubSpec: S3 as unknown,
  CrossRef: S4 as unknown,
  AgentAllocation: S5 as unknown,
  Team: S6 as unknown,
  Reviewer: S7 as unknown,
  OpenQuestion: S8 as unknown,
  Risk: S9 as unknown,
  Mockup: S10 as unknown,
  Chart: S11 as unknown,
  AgentTree: S12 as unknown,
};

export const componentNames: ComponentName[] = [
  'Status',
  'Phase',
  'Timeline',
  'SubSpec',
  'CrossRef',
  'AgentAllocation',
  'Team',
  'Reviewer',
  'OpenQuestion',
  'Risk',
  'Mockup',
  'Chart',
  'AgentTree',
];
