import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createGenerator, type Config } from 'ts-json-schema-generator';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const outDir = resolve(pkgRoot, 'schemas');
mkdirSync(outDir, { recursive: true });

interface ComponentEntry {
  name: string;
  file: string;
  type: string;
}

const components: ComponentEntry[] = [
  { name: 'Status', file: 'src/components/Status.tsx', type: 'StatusProps' },
  { name: 'Phase', file: 'src/components/Phase.tsx', type: 'PhaseProps' },
  { name: 'Timeline', file: 'src/components/Timeline.tsx', type: 'TimelineProps' },
  { name: 'SubSpec', file: 'src/components/SubSpec.tsx', type: 'SubSpecProps' },
  { name: 'CrossRef', file: 'src/components/CrossRef.tsx', type: 'CrossRefProps' },
  {
    name: 'AgentAllocation',
    file: 'src/components/AgentAllocation.tsx',
    type: 'AgentAllocationProps',
  },
  { name: 'Team', file: 'src/components/Team.tsx', type: 'TeamProps' },
  { name: 'Reviewer', file: 'src/components/Reviewer.tsx', type: 'ReviewerProps' },
  { name: 'OpenQuestion', file: 'src/components/OpenQuestion.tsx', type: 'OpenQuestionProps' },
  { name: 'Risk', file: 'src/components/Risk.tsx', type: 'RiskProps' },
  { name: 'Mockup', file: 'src/components/Mockup.tsx', type: 'MockupProps' },
  { name: 'Chart', file: 'src/components/Chart.tsx', type: 'ChartProps' },
];

function stripChildrenAndPrune(schema: Record<string, unknown>) {
  const definitions = (schema.definitions ?? {}) as Record<string, Record<string, unknown>>;
  for (const def of Object.values(definitions)) {
    if (def.properties && typeof def.properties === 'object') {
      const props = def.properties as Record<string, unknown>;
      delete props.children;
    }
    if (Array.isArray(def.required)) {
      def.required = (def.required as string[]).filter((r) => r !== 'children');
    }
  }
  const reachable = new Set<string>();
  const queue: unknown[] = [schema];
  while (queue.length) {
    const node = queue.shift();
    if (!node || typeof node !== 'object') continue;
    for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
      if (key === '$ref' && typeof value === 'string') {
        const name = value.replace('#/definitions/', '');
        if (!reachable.has(name)) {
          reachable.add(name);
          if (definitions[name]) queue.push(definitions[name]);
        }
      } else if (typeof value === 'object') {
        queue.push(value);
      }
    }
  }
  for (const key of Object.keys(definitions)) {
    if (!reachable.has(key)) delete definitions[key];
  }
  if (Object.keys(definitions).length === 0) {
    delete (schema as Record<string, unknown>).definitions;
  }
}

const tsconfig = resolve(pkgRoot, 'tsconfig.json');

for (const { name, file, type } of components) {
  const config: Config = {
    path: resolve(pkgRoot, file),
    type,
    tsconfig,
    skipTypeCheck: true,
    expose: 'export',
    jsDoc: 'extended',
  };
  const generator = createGenerator(config);
  const schema = generator.createSchema(type) as Record<string, unknown>;
  stripChildrenAndPrune(schema);
  const outPath = resolve(outDir, `${name}.schema.json`);
  writeFileSync(outPath, `${JSON.stringify(schema, null, 2)}\n`);
  console.log(`✓ ${name} -> ${outPath}`);
}

const indexBody = `// AUTO-GENERATED by scripts/generate-schemas.ts — do not edit by hand.
${components.map(({ name }, idx) => `import S${idx} from '../schemas/${name}.schema.json';`).join('\n')}

export type ComponentName =
${components.map(({ name }) => `  | '${name}'`).join('\n')};

export const schemas: Record<ComponentName, unknown> = {
${components.map(({ name }, idx) => `  ${name}: S${idx} as unknown,`).join('\n')}
};

export const componentNames: ComponentName[] = [
${components.map(({ name }) => `  '${name}',`).join('\n')}
];
`;

writeFileSync(resolve(pkgRoot, 'src/schemas-index.ts'), indexBody);
console.log('✓ schemas-index.ts written');
