export { atomicWriteJson } from './atomic.js';
export { isReviewCoreError, ReviewCoreError, type ReviewCoreErrorCode } from './errors.js';
export { hashText } from './hash.js';
export {
  capturePr,
  captureReviewSource,
  captureScope,
  captureStaged,
  captureUnstaged,
  compareReviewSourceFreshness,
  recaptureReviewSource,
  repositoryName,
  resolveRepositoryRoot,
  systemCommandRunner,
  type CapturedReviewSource,
  type CaptureFileOptions,
  type CapturePrOptions,
  type CaptureReviewSourceRequest,
  type CaptureScopeOptions,
  type CommandResult,
  type CommandRunner,
  type ReviewCaptureSourceRequest,
  type ReviewSourceFreshness,
} from './source-capture.js';
export {
  compareReviewSourceFreshnessAsync,
  ReviewFreshnessAsyncError,
  type ReviewFreshnessAsyncErrorCode,
  type ReviewFreshnessWorker,
  type ReviewFreshnessWorkerData,
  type ReviewFreshnessWorkerFactory,
  type ReviewFreshnessWorkerInput,
  type ReviewSourceFreshnessAsyncOptions,
} from './source-capture-async.js';
export { reconciliationKey, reconcileReview } from './reconcile.js';
export { resolveReviewItemContext, resolveReviewLineSelection } from './review-lines.js';
export { deriveReviewReadiness } from './readiness.js';
export {
  buildDiffSnapshot,
  createHunkReviewItem,
  parseUnifiedDiff,
  type BuildDiffSnapshotInput,
} from './diff.js';
export {
  applyCodeSections,
  buildScopeSnapshot,
  type BuildScopeSnapshotInput,
  type ProposedCodeSection,
} from './scope.js';
export { SAFE_SEGMENT, assertSafeReviewSegment, formatReviewRef, parseReviewRef } from './ids.js';
export {
  answersDir,
  insightsFile,
  progressFile,
  questionsDir,
  reviewRevisionDir,
  reviewWorkspaceDir,
  reviewsDir,
  snapshotFile,
  workspaceFile,
} from './paths.js';
export {
  assertReviewAnswer,
  assertReviewInsights,
  assertReviewProgress,
  assertReviewQuestion,
  assertReviewQuestionEnvelope,
  assertReviewQuestionGeneration,
  assertReviewSnapshot,
  assertReviewWorkspace,
  reviewAnswerSchema,
  reviewInsightsSchema,
  reviewProgressSchema,
  reviewQuestionSchema,
  reviewQuestionEnvelopeSchema,
  reviewQuestionGenerationSchema,
  reviewSnapshotSchema,
  reviewWorkspaceSchema,
} from './schema.js';
export { createReviewStore, type ReviewStore, type ReviewStoreOptions } from './store.js';
export {
  claimQuestion,
  claimQuestions,
  createQuestionQueue,
  enqueueQuestion,
  failQuestion,
  listQuestions,
  reconcileExpiredQuestions,
  releaseClaim,
  removeReviewListener,
  renewClaim,
  reviewQuestionsDirectory,
  touchReviewListener,
  writeAnswer,
  type ClaimResult,
  type QuestionQueue,
  type ReviewQuestionInput,
  type QuestionPersistenceOptions,
  type QuestionPublication,
} from './questions.js';
export type {
  DiffFile,
  DiffFileStatus,
  DiffHunk,
  DiffLine,
  DiffLineKind,
  DiffReviewSnapshot,
  ReviewAnswer,
  ActiveReviewPointer,
  ReviewBundle,
  ReviewClaim,
  ReviewFileInsight,
  ReviewGroup,
  ReviewInsightConfidence,
  ReviewInsights,
  ReviewItem,
  ReviewItemContext,
  ReviewItemInsight,
  ReviewItemKind,
  ReviewItemProgress,
  ReviewItemProgressPatch,
  ReviewItemStatus,
  ReviewDiffLineRow,
  ReviewLineRow,
  ReviewLineSelection,
  ReviewProgress,
  ReviewProgressUpdate,
  ReviewQuestion,
  ReviewQuestionEnvelope,
  ReviewQuestionGeneration,
  ReviewQuestionGenerationState,
  ReviewAnswerReference,
  ReviewQuestionStatus,
  ReviewReadiness,
  ReviewRange,
  ReviewRef,
  ReviewRepository,
  ReviewSnapshot,
  ReviewScopeLineRow,
  ReviewSource,
  ReviewWorkspace,
  ScopeReviewSnapshot,
  SourceFile,
  SourceLine,
  WalkthroughPosition,
} from './types.js';
