import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { dim, green } from 'kleur/colors';
import { resolveProjectPaths } from './paths.js';
import { generateSessionName, uniqueSessionName } from './session-name.js';

export type SpecType = 'feature' | 'refactor' | 'project';

const VALID_TYPES: SpecType[] = ['feature', 'refactor', 'project'];

export function isSpecType(t: string): t is SpecType {
  return (VALID_TYPES as string[]).includes(t);
}

interface SpecOptions {
  title: string;
  type: SpecType;
  /** Explicit session name override. Skips auto-generation. */
  sessionName?: string;
  root?: string;
  now?: Date;
}

export interface SpecResult {
  sessionDir: string;
  sessionName: string;
  files: string[];
}

const OVERVIEW_TEMPLATE = (title: string, type: SpecType) => `---
title: '${title.replace(/'/g, "\\'")}'
type: ${type}
---

import { Status, Phase, Timeline, SubSpec, CrossRef, AgentAllocation, Risk, OpenQuestion } from '@synergy/spec-kit';

# ${title}

<Status value="draft" note="Auto-generated by \`synergy spec\`" />

## Summary

_Replace this with a one-paragraph description of the work._

## Goals

- _What success looks like._
- _Out of scope: ..._

## Sub-specs

<SubSpec slug="01-architecture" title="Architecture" summary="High-level structure and components." />
<SubSpec slug="02-implementation" title="Implementation Plan" summary="Phased build with dependencies." />

## Open questions

<OpenQuestion id="Q1" question="What is the primary constraint?">
  Document the unknown here.
</OpenQuestion>

## Risks

<Risk id="R1" severity="medium" title="Scope creep">
  Mitigation: cut scope ruthlessly in the implementation plan.
</Risk>
`;

const ARCHITECTURE_TEMPLATE = (_title: string) => `---
title: 'Architecture'
---

import { Chart, CrossRef, Mockup } from '@synergy/spec-kit';

# Architecture

See <CrossRef to="00-overview">overview</CrossRef> for context.

## System diagram

<Chart kind="flow" caption="High-level data flow">
{\`graph LR
  A[Client] --> B[API]
  B --> C[Database]
  B --> D[Worker]\`}
</Chart>

## Components

_Describe each component, its responsibilities, and interfaces._
`;

const IMPLEMENTATION_TEMPLATE = (_title: string) => `---
title: 'Implementation Plan'
---

import { Phase, Timeline, AgentAllocation, Status } from '@synergy/spec-kit';

# Implementation Plan

<Phase number={1} title="Foundation" status="proposed" estimate="0.5d" summary="Scaffolding and shared types.">
  - Decisions to lock down.
  - Files to create.
</Phase>

<Phase number={2} title="Core" status="proposed" estimate="1d">
  - The bulk of the work.
</Phase>

<Phase number={3} title="Polish" status="proposed" estimate="0.5d">
  - Tests, docs, examples.
</Phase>

## Agent allocation

<AgentAllocation
  context="Sub-agents own independent phases; humans review."
  entries={[
    { name: 'core-impl', type: 'sub-agent', responsibility: 'Phase 1 & 2 implementation', phases: [1, 2] },
    { name: 'reviewer', type: 'human', responsibility: 'PR review + acceptance', phases: [1, 2, 3] }
  ]}
/>

## Timeline

<Timeline
  milestones={[
    { label: 'Plan approved', status: 'proposed' },
    { label: 'Phase 1 complete', status: 'draft' },
    { label: 'Phase 2 complete', status: 'draft' },
    { label: 'Ready to ship', status: 'draft' }
  ]}
/>
`;

const ORCHESTRATOR_TEMPLATE = (title: string, type: SpecType, sessionName: string) => `# Orchestrator — ${title}

> **Read this first** before implementing any of the specs in this session.
> Session: \`${sessionName}\`. Type: \`${type}\`.

## Overview

_One paragraph: what is being built, why, and what the success criteria are._

## Dependency graph

Implementation order — items on the same line can run in parallel.

\`\`\`
Phase 1 (foundation)
  └─> Phase 2 (core) ┐
                     ├─> Phase 3 (polish)
  └─> Phase ?  ──────┘
\`\`\`

## Parallel chunks

- **Sequential gate:** Phase 1 must land first; nothing else may start.
- **Parallelizable:** _List the phases or chunks that can run as parallel sub-agents._

## Agent strategy

- **Use sub-agents (single-shot, isolated work)** for: file-bounded implementation tasks where the interface is already specified.
- **Use an agent team (multi-step, exploratory)** for: cross-cutting concerns, debugging, integration testing.
- **Keep human in the loop** at every phase boundary: present a diff, run tests, get approval.

## Verification gates

- After Phase 1: \`pnpm build\` clean, types resolve.
- After Phase 2: feature works end-to-end against a smoke test.
- After Phase 3: docs + examples shipped, CI green.

## How to invoke

Reference this session in Claude Code with:

\`\`\`
Implement the plan in @.synergy/sessions/${sessionName}/
Start with orchestrator.md, then walk the specs in order.
\`\`\`
`;

export function createSpec(opts: SpecOptions): SpecResult {
  const paths = resolveProjectPaths(opts.root);
  mkdirSync(paths.sessionsDir, { recursive: true });

  const baseName = opts.sessionName ?? generateSessionName(opts.title, opts.now);
  const sessionName = uniqueSessionName(paths.sessionsDir, baseName, opts.title);
  const sessionDir = join(paths.sessionsDir, sessionName);
  mkdirSync(sessionDir, { recursive: true });
  mkdirSync(join(sessionDir, '_components'), { recursive: true });
  mkdirSync(join(sessionDir, 'assets'), { recursive: true });

  const files: Array<{ name: string; body: string }> = [
    { name: '00-overview.mdx', body: OVERVIEW_TEMPLATE(opts.title, opts.type) },
    { name: '01-architecture.mdx', body: ARCHITECTURE_TEMPLATE(opts.title) },
    { name: '02-implementation.mdx', body: IMPLEMENTATION_TEMPLATE(opts.title) },
    { name: 'orchestrator.md', body: ORCHESTRATOR_TEMPLATE(opts.title, opts.type, sessionName) },
  ];

  const written: string[] = [];
  for (const f of files) {
    const path = join(sessionDir, f.name);
    writeFileSync(path, f.body);
    written.push(path);
  }

  process.stdout.write(green('✓') + ` Created session ` + dim(sessionName) + `\n`);
  for (const path of written) {
    process.stdout.write('  ' + dim(path.replace(`${paths.root}/`, '')) + '\n');
  }
  return { sessionDir, sessionName, files: written };
}
